# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Maieuta
email: maieuta.it@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A intelixencia artificial está a piques de revolucionar o sistema educativo. Ante o progresivo distanciamento entre a educación e a sociedade, nós cremos que a integración da intelixencia artificial nos procesos de ensino-aprendizaxe é a chave para traer de volta a relevancia e o significado á experiencia educativa. Xa non abonda con preparar o alumnado para carreiras tradicionais - precisamos desenvolver enfoques de aprendizaxe que aproveiten a diversidade do estudantado, transformando a aula nun espazo vivo e envolvente. Imaxine identificar e atender ás necesidades particulares da mocidade de forma precisa, proactiva e non invasiva. Esa é a nosa misión - modernizar a educación a través da intelixencia artificial, tornándoa verdadeiramente centrada no alumnado e adaptada ás esixencias do século XXI.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  maieuta

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
